config/routes.rb
Rails.application.routes.draw do
  resources :waybills
  resources :user_addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    collection do 
      get :reset_password
      put :change_current_city
      get :user_card_logs
      get :coupons
    end
  end

  resources :categories, only: [:index, :show]


  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders do
  end

  resources :user_card_charge_settings, only: [:index] do 
    member do 
      post :pay
    end
  end

  resources :vouchers do 
    member do 
      get :pay
    end
  end
  
end

app/controllers/user_addresses_controller.rb
class UserAddressesController < ApplicationController
  before_action :set_user_address, only: [:show, :edit, :update, :destroy]

  # GET /user_addresses
  # GET /user_addresses.json
  def index
    @user_addresses = current_user.user_addresses
  end

  # GET /user_addresses/1
  # GET /user_addresses/1.json
  def show
  end

  # GET /user_addresses/new
  def new
    @user_address = UserAddress.new
    @user_address.build_address
  end

  # GET /user_addresses/1/edit
  def edit
  end

  # POST /user_addresses
  # POST /user_addresses.json
  def create
    @user_address = UserAddress.new(user_address_params.merge(city: current_city, user: current_user))

    respond_to do |format|
      if @user_address.save
        format.html { redirect_to user_addresses_path, notice: 'User address was successfully created.' }
      else
        format.json { render json: @user_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_addresses/1
  # PATCH/PUT /user_addresses/1.json
  def update
    respond_to do |format|
      if @user_address.update(user_address_params)
        format.html { redirect_to user_addresses_path, notice: 'User address was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /user_addresses/1
  # DELETE /user_addresses/1.json
  def destroy
    @user_address.destroy
    respond_to do |format|
      format.html { redirect_to user_addresses_path, notice: 'User address was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_address
      @user_address = UserAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_address_params
      ret = params.require(:user_address).permit(:name, address_attributes: [:id, :address, :comment, :lat, :lng])
      ret[:address_attributes].delete(:address) if ret[:address_attributes][:address].blank?
      ret
    end
end

app/helpers/user_addresses_helper.rb
module UserAddressesHelper
end

app/views/user_addresses/_form.html.slim
<div class="formIn">
= simple_form_for(@user_address) do |f|
  = f.error_notification

  .form-inputs 
    = f.input :name
    = f.simple_fields_for :address do |a|
      = a.input :address, as: :select
      = a.input :comment
      = a.input :lat
      = a.input :lng

  .form-actions 
    = f.button :submit 
</div>

javascript:
  $(function(){
    $("#user_address_address_attributes_address").select2({
      placeholder: "输入一个地址",
      theme: 'bootstrap',
      ajax: {
        url: '/addresses/suggestion.json',
        dataType: 'json',
        delay: 250,
        cache: false
      },
      minimumInputLength: 1
    })
    $("#user_address_address_attributes_address").on("change", function (e) {
      var data = $("#user_address_address_attributes_address").select2('data')[0];
      if(data){
        $("#user_address_address_attributes_lat").val(data['lat'])
        $("#user_address_address_attributes_lng").val(data['lng'])
      }
    });
  })

app/views/user_addresses/edit.html.slim
h1 Editing user_address

== render 'form'

=> link_to 'Show', @user_address
'|
=< link_to 'Back', user_addresses_path

app/views/user_addresses/index.html.slim
h1 Listing user_addresses
.panel.panel-default 
  .panel-body
    table.table.table-stripted
      thead
        tr
          th Address
          th Comment
          th Lat
          th Lng
          th
          th
          th

      tbody
        - @user_addresses.each do |user_address|
          tr
            td = user_address.name
            td = user_address.address.comment
            td = user_address.address.lat
            td = user_address.address.lng
            td = link_to 'Show', user_address
            td = link_to 'Edit', edit_user_address_path(user_address)
            td = link_to 'Destroy', user_address, data: { confirm: 'Are you sure?' }, method: :delete

br
<div class="address">
  = link_to 'New User address', new_user_address_path
</div>

app/views/user_addresses/new.html.slim
h1 New user_address

== render 'form'

= link_to 'Back', user_addresses_path

app/views/user_addresses/show.html.slim
p#notice = notice

p
  strong User:
  = @user_address.user
p
  strong Name:
  = @user_address.name

=> link_to 'Edit', edit_user_address_path(@user_address)
'|
=< link_to 'Back', user_addresses_path