config/routes.rb
Rails.application.routes.draw do
  resources :waybills
  resources :user_addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    collection do 
      get :reset_password
      put :change_current_city
      get :user_card_logs
      get :coupons
    end
  end

  resources :categories, only: [:index, :show]


  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders do
  end

  resources :user_card_charge_settings, only: [:index] do 
    member do 
      post :pay
    end
  end

  resources :vouchers do 
    member do 
      get :pay
    end
  end
  
end

app/models/user_card_charge_setting.rb
class UserCardChargeSetting < ApplicationRecord
end

app/controllers/user_card_charge_settings_controller.rb
class UserCardChargeSettingsController < ApplicationController
  before_action :set_user_card_charge_setting, only: [:pay]

  
  def index
    @user_card_charge_settings = UserCardChargeSetting.all
  end

  def pay
    current_user.user_card.charge(@user_card_charge_setting)
    respond_to do |format|
      format.html { redirect_to user_home_path, notice: 'User card charge setting was successfully created.' }
    end
  end

  private

  def set_user_card_charge_setting
    @user_card_charge_setting = UserCardChargeSetting.find(params[:id])
  end

end

app/helpers/user_card_charge_settings_helper.rb
module UserCardChargeSettingsHelper
end

app/views/user_card_charge_settings/_form.html.slim
<div class="formIn">
= simple_form_for(@user_card_charge_setting) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit
</div>

app/views/user_card_charge_settings/edit.html.slim
h1 Editing user_card_charge_setting

== render 'form'

=> link_to 'Show', @user_card_charge_setting
'|
=< link_to 'Back', user_card_charge_settings_path

app/views/user_card_charge_settings/index.html.slim
.row
    .col-md-12
      .panel.panel-default
        .panel-heading
          | 充值优惠
        .panel-body
          table.table.table-striped
            - @user_card_charge_settings.each do |user_card_charge_setting|
              tr
                td = "冲 #{user_card_charge_setting.min} 送 #{user_card_charge_setting.money_give}"
                td = link_to '充值', pay_user_card_charge_setting_path(user_card_charge_setting), method: :post

app/views/user_card_charge_settings/new.html.slim
h1 New user_card_charge_setting

== render 'form'

= link_to 'Back', user_card_charge_settings_path

app/views/user_card_charge_settings/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_user_card_charge_setting_path(@user_card_charge_setting)
'|
=< link_to 'Back', user_card_charge_settings_path