config/routes.rb
Rails.application.routes.draw do
  resources :waybills
  resources :user_addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    collection do 
      get :reset_password
      put :change_current_city
      get :user_card_logs
      get :coupons
    end
  end

  resources :categories, only: [:index, :show]


  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders do
  end

  resources :user_card_charge_settings, only: [:index] do 
    member do 
      post :pay
    end
  end

  resources :vouchers do 
    member do 
      get :pay
    end
  end
  
end

app/models/waybill.rb
class Waybill < ApplicationRecord
  belongs_to :order

  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  belongs_to :from_address, class_name: Address
  belongs_to :to_address, class_name: Address

  include Workflow

  workflow_column :status 

  workflow do
    state :new do
      event :accept, transitions_to: :accepted
      event :reject, transitions_to: :rejected
    end
    state :accepted do
      event :finish, transitions_to: :finished
      event :reject, transitions_to: :reject
    end
    state :rejected
    state :finished
  end

  def accept
    self.order.next!
  end

  def finish
    self.order.next!
  end

  def reject
    self.order.prev!
  end
end

app/helpers/waybills_helper.rb
module WaybillsHelper
  def show_waybill_status(status)
    case status
    when 'new'
      '初始'
    when 'accepted'
      '已接单'
    when 'rejected'
      '已拒单'
    when 'finished'
      '已完成'
    end
  end
end

app/views/waybills/_form.html.slim
<div class="formIn">
= simple_form_for(@waybill) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit
</div>

app/views/waybills/edit.html.slim
h1 Editing waybill

== render 'form'

=> link_to 'Show', @waybill
'|
=< link_to 'Back', waybills_path

app/views/waybills/index.html.slim
h1 Listing waybills

table
  thead
    tr
      th
      th
      th

  tbody
    - @waybills.each do |waybill|
      tr
        td = link_to 'Show', waybill
        td = link_to 'Edit', edit_waybill_path(waybill)
        td = link_to 'Destroy', waybill, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Waybill', new_waybill_path

app/views/waybills/new.html.slim
h1 New waybill

== render 'form'

= link_to 'Back', waybills_path

app/views/waybills/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_waybill_path(@waybill)
'|
=< link_to 'Back', waybills_path