config/routes.rb
Rails.application.routes.draw do
  resources :waybills
  resources :user_addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    collection do 
      get :reset_password
      put :change_current_city
      get :user_card_logs
      get :coupons
    end
  end

  resources :categories, only: [:index, :show]


  get '/home/user', to: 'home#user', as: 'user_home'

  root to: 'categories#index'

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :orders do
  end

  resources :user_card_charge_settings, only: [:index] do 
    member do 
      post :pay
    end
  end

  resources :vouchers do 
    member do 
      get :pay
    end
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :price_rules

  def get_price_rule(city_id)
    self.price_rules.where('city_id = ? and from_date <= ?', city_id, Date.today).order(from_date: :desc).first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = current_city.categories.where(is_del: 0)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @price_rule = @category.get_price_rule(current_city)
    @products = @category.products.where(is_del: 0).paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

end

app/views/categories/_category_block.html.slim
  = link_to image_tag("#{qiniu_url(category.logo)}", size: '150x150'), category_path(category)

app/views/categories/index.html.slim
<body>
.row 
  ul.nav.navbar-nav.ieCss.pull-right role="presentation"
    .dropdown
      span style="font-size:14px; color:#777" = current_city['name']
      button.btn.dropdown-toggler type='button' data-toggle='dropdown' style='background:none' &#9660
      ul.dropdown-menu role='menu' aria-labelledby="dropdownMenu1"
        - City.all.each do |city|
          li role="presentation"
            = link_to city.name, change_current_city_users_path(city_id: city.id), method: :put
<div class="homeinfo">
- @categories.each_slice(2).each do |categories|

  - categories.each do |category|
      <div class="container gallery-container" style="display: inline-block; float: left;width: 33%;">
        <div class="tz-gallery" style="width: 100%;">
          <div class="row_1">
              <div class="col-sm-6 col-md-4" style="width: 100%;">
                <div class="thumbnail">
                  col-xs-6
                  <a class="lightbox" >
                    = render partial: 'categories/category_block', locals: {category: category}                  
                  </a>
                  <div class="caption">
                    <h3>
                    = category.name
                    </h3>
                  </div>    
                </div>
              </div>
          </div>
        </div>
      </div>
</div>
</body>

app/views/categories/new.html.slim
h2
  | Resend confirmation instructions
= simple_form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f|
  = f.error_notification
  = f.full_error :confirmation_token
  .form-inputs
    = f.input :email, required: true, autofocus: true
  .form-actions
    = f.button :submit, "Resend confirmation instructions"
= render "devise/shared/links"

app/views/categories/show.html.slim
- @products.each_slice(2).each do |products|
  .row 
    - products.each do |product|
      .col-xs-6
        = render partial: 'products/product', locals: {product: product}
  br

= will_paginate @products, renderer: BootstrapPagination::Rails

= link_to '下单', new_order_path(category: @category), class: 'btn btn-info btn-sm'